name: QDistRnd
version: "0.8.3"
license: "GPL-2.0-or-later"
date: 2022-03-21
description: |
    Calculate the distance of a q-ary quantum stabilizer code

authors:
    - name: Leonid P. Pryadko
      url: http://faculty.ucr.edu/~leonid
    - name: Vadim A. Shabashov
      url: https://sites.google.com/view/vadim-shabashov/

maintainers:
    - name: Leonid P. Pryadko
      url: http://faculty.ucr.edu/~leonid
    - name: Vadim A. Shabashov
      url: https://sites.google.com/view/vadim-shabashov/
    - name: Valerii K. Kozin
      url: mailto:kozin.valera@gmail.com

GAP: "4.11"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "AutoDoc"
      version: "1.5"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "Guava"
      version: "3.14"
      url: "https://gap-packages.github.io/guava"

www: https://QEC-pages.github.io/qdistrnd
readme: README.md
packageinfo: https://QEC-pages.github.io/qdistrnd/PackageInfo.g

downloads:
    - name: tar.gz
      url: https://github.com/QEC-pages/QDistRnd/releases/download/v0.8.3/qdistrnd-0.8.3tar.gz

abstract: |
    The GAP package <code>QDistRnd</code> 
    implements a probabilistic algorithm for finding the 
    minimum distance of a quantum code linear over a finite
    field GF(<var>q</var>).

status: other
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    QECC, quantum code, stabilizer code, quantum error correcting code, distance.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>PSK22</span>]   <b class='BibAuthor'>Pryadko, L. P., Shabashov, V. A. and Kozin, V. K.</b>,
     <i class='BibTitle'>QDistRnd, Calculate the distance of a q-ary quantum stabilizer code,
             Version 0.8.3</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://QEC-pages.github.io/qdistrnd">https://QEC-pages.github.io/qdistrnd</a></span>.
    </p>
    

bibtex: |
    @misc{ QDistRnd0.8.3,
      author =           {Pryadko, L. P. and Shabashov, V. A. and Kozin, V. K.},
      title =            {{QDistRnd},  Calculate the distance of a q-ary quantum
                          stabilizer code, {V}ersion 0.8.3},
      month =            {Mar},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href           {https://QEC-pages.github.io/qdistrnd}
                          {\texttt{https://QEC-pages.github.io/}\discretionary
                          {}{}{}\texttt{qdistrnd}}},
      keywords =         {QECC;  quantum  code;  stabilizer  code; quantum error
                          correcting code; distance},
      printedkey =       {PSK22}
    }

